apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
    - name: redis-ui
      port: 8001
      targetPort: 8001
  selector:
    app: {{ include "redis.fullname" . }}
