apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: my-app
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
    - name: redis-ui
      port: 8001
      targetPort: 8001
  selector:
    app: my-app